STORAGE:
  PATH: development/output/synthesizer_demo

SYNTHESIZER:
  CHARACTERISTICS:
    FUNCTION: gaussian_copula
    PARAMS:
      training_data_path: training_products.csv
      num_rows: 20
      seed: 42
