STORAGE:
  PATH: output/product_details_demo

RULE:
  PRODUCTS:
    FUNCTION: simulate_products_rule_based
    PARAMS:
      num_products: 5
      seed: 42
  METRICS:
    FUNCTION: simulate_metrics_rule_based
    PARAMS:
      date_start: "2024-11-01"
      date_end: "2024-11-07"
      sale_prob: 0.5
      granularity: "daily"

PRODUCT_DETAILS:
  FUNCTION: simulate_product_details_mock
