STORAGE:
  PATH: output/custom_demo

RULE:
  PRODUCTS:
    FUNCTION: electronics_only
    PARAMS:
      num_products: 30
  METRICS:
    FUNCTION: simulate_metrics_rule_based
    PARAMS:
      date_start: "2024-11-01"
      date_end: "2024-11-30"
      sale_prob: 0.6
      granularity: "daily"
