STORAGE:
  PATH: output/synthesizer_demo

SYNTHESIZER:
  PRODUCTS:
    FUNCTION: gaussian_copula
    PARAMS:
      training_data_path: training_products.csv
      num_rows: 20
      seed: 42
  METRICS:
    FUNCTION: gaussian_copula
    PARAMS:
      training_data_path: training_sales.csv
      num_rows: 100
      seed: 42
